/* =====================================================
DATABASE EXPLORATION
===================================================== */

--- Explore All Objects in The Database
SELECT *
FROM INFORMATION_SCHEMA.TABLES;

--- Explore All Columns in a Specific Table
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';


/* =====================================================
CUSTOMER EXPLORATION
===================================================== */

--- Explore All Countries Our Customers Come From
SELECT DISTINCT country
FROM Gold.dim_customers;

--- Explore the Oldest and Youngest Customer
SELECT 
    MAX(birthdate) AS Youngest_customer,
    DATEDIFF(YEAR, MAX(birthdate), GETDATE()) AS Year_of_youngest,
    MIN(birthdate) AS Oldest_Customer,
    DATEDIFF(YEAR, MIN(birthdate), GETDATE()) AS Year_of_oldest
FROM Gold.dim_customers;

--- Find Total Customers
SELECT COUNT(customer_key) AS Total_Customers
FROM Gold.dim_customers;

--- Find Total Customers Who Placed Orders
SELECT COUNT(DISTINCT customer_key) AS Customers_With_Orders
FROM Gold.fact_sales;

--- Find Total Customers by Country
SELECT 
    country,
    COUNT(customer_key) AS total_customer
FROM Gold.dim_customers
GROUP BY country
ORDER BY total_customer DESC;

--- Find Total Customers by Gender
SELECT 
    gender,
    COUNT(customer_key) AS total_customer
FROM Gold.dim_customers
GROUP BY gender
ORDER BY total_customer DESC;


/* =====================================================
PRODUCT EXPLORATION
===================================================== */

--- Explore Product Hierarchy
SELECT DISTINCT
    category,
    subcategory,
    product_name
FROM Gold.dim_products
ORDER BY 1,2,3;

--- Find Total Number of Products
SELECT COUNT(DISTINCT product_key) AS Total_Products
FROM Gold.dim_products;

--- Find Total Products by Category
SELECT
    category,
    COUNT(product_key) AS total_product
FROM Gold.dim_products
GROUP BY category
ORDER BY total_product DESC;

--- Average Product Cost by Category
SELECT
    category,
    AVG(product_cost) AS average_cost
FROM Gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;


/* =====================================================
SALES EXPLORATION
===================================================== */

--- Find the First and Last Order Date
--- Calculate How Many Years of Sales Are Available
SELECT 
    MIN(order_date) AS First_order_date,
    MAX(order_date) AS Last_order_date,
    DATEDIFF(YEAR, MIN(order_date), MAX(order_date)) AS years_of_sales
FROM Gold.fact_sales;

--- Find Total Sales
SELECT 
    SUM(sales_amount) AS Total_Sales
FROM Gold.fact_sales;

--- Find Total Quantity Sold
SELECT 
    SUM(quantity) AS Total_items
FROM Gold.fact_sales;

--- Find Average Selling Price
SELECT 
    AVG(price) AS Average_price
FROM Gold.fact_sales;

--- Find Total Number of Orders
SELECT 
    COUNT(DISTINCT order_number) AS Total_Orders
FROM Gold.fact_sales;


/* =====================================================
BUSINESS METRICS REPORT
===================================================== */

--- Generate a Report Showing Key Business Metrics
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value
FROM Gold.fact_sales

UNION ALL

SELECT 'Total Quantity', SUM(quantity)
FROM Gold.fact_sales

UNION ALL

SELECT 'Average Price', AVG(price)
FROM Gold.fact_sales

UNION ALL

SELECT 'Total Orders', COUNT(DISTINCT order_number)
FROM Gold.fact_sales

UNION ALL

SELECT 'Total Products', COUNT(product_name)
FROM Gold.dim_products

UNION ALL

SELECT 'Total Customers', COUNT(customer_key)
FROM Gold.dim_customers;


/* =====================================================
REVENUE ANALYSIS
===================================================== */

--- Total Revenue Generated by Category
SELECT
    dp.category,
    SUM(fs.sales_amount) AS Total_revenue
FROM Gold.fact_sales fs
LEFT JOIN Gold.dim_products dp
    ON dp.product_key = fs.product_key
GROUP BY dp.category
ORDER BY Total_revenue DESC;

--- Total Revenue Generated by Customer
SELECT
    dc.customer_key,
    dc.first_name,
    dc.last_name,
    SUM(fs.sales_amount) AS Total_revenue
FROM Gold.fact_sales fs
LEFT JOIN Gold.dim_customers dc
    ON dc.customer_key = fs.customer_key
GROUP BY dc.customer_key, dc.first_name, dc.last_name
ORDER BY Total_revenue DESC;

--- Distribution of Sold Items Across Countries
SELECT
    dc.country,
    SUM(fs.quantity) AS Total_sold_items
FROM Gold.fact_sales fs
LEFT JOIN Gold.dim_customers dc
    ON dc.customer_key = fs.customer_key
GROUP BY dc.country
ORDER BY Total_sold_items DESC;


/* =====================================================
TOP PRODUCTS ANALYSIS
===================================================== */

--- Top 5 Products by Revenue
SELECT TOP(5)
    dp.product_name,
    SUM(fs.sales_amount) AS Total_revenue
FROM Gold.fact_sales fs
LEFT JOIN Gold.dim_products dp
    ON dp.product_key = fs.product_key
GROUP BY dp.product_name
ORDER BY Total_revenue DESC;

--- Top 5 Products Using Ranking
SELECT *
FROM (
    SELECT
        dp.product_name,
        SUM(fs.sales_amount) AS Total_revenue,
        RANK() OVER(ORDER BY SUM(fs.sales_amount) DESC) AS rank_products
    FROM Gold.fact_sales fs
    LEFT JOIN Gold.dim_products dp
        ON dp.product_key = fs.product_key
    GROUP BY dp.product_name
) t
WHERE rank_products <= 5;

--- 5 Worst Performing Products
SELECT TOP(5)
    dp.product_name,
    SUM(fs.sales_amount) AS Total_revenue
FROM Gold.fact_sales fs
LEFT JOIN Gold.dim_products dp
    ON dp.product_key = fs.product_key
GROUP BY dp.product_name
ORDER BY Total_revenue;


/* =====================================================
CUSTOMER PERFORMANCE
===================================================== */

--- Top 10 Customers by Revenue
SELECT *
FROM (
    SELECT
        dc.customer_key,
        dc.first_name,
        dc.last_name,
        SUM(fs.sales_amount) AS Total_revenue,
        ROW_NUMBER() OVER(ORDER BY SUM(fs.sales_amount) DESC) AS rank_customer
    FROM Gold.fact_sales fs
    LEFT JOIN Gold.dim_customers dc
        ON dc.customer_key = fs.customer_key
    GROUP BY dc.customer_key, dc.first_name, dc.last_name
) t
WHERE rank_customer <= 10;

--- 3 Customers With the Fewest Orders
SELECT TOP 3
    dc.customer_key,
    dc.first_name,
    dc.last_name,
    COUNT(DISTINCT fs.order_number) AS Total_orders
FROM Gold.fact_sales fs
LEFT JOIN Gold.dim_customers dc
    ON dc.customer_key = fs.customer_key
GROUP BY dc.customer_key, dc.first_name, dc.last_name
ORDER BY Total_orders;
